### ISSUE TITLE
How can I fix it?

### ISSUE THREAD

**Issue by Axripov** [hasoart/ascii_converter#1]
0 : видео 2
Choose which video to convert: 0
Traceback (most recent call last):
  File ".\frames_to_ascii_file.py", line 25, in <module>
    first_frame = cv2.imread(video_path + video_path_listdir[0])
IndexError: list index out of range

**Comment by hasoart** [comment]
It's because there are Cyrillic letters in the video path. Rename the folder 'видео 2' so that it only contains English symbols, and it should work properly. If have put the program folder in a path which also contains Cyrillic letters try to put the program in an appropriate path. That'll do the job until I fix the problem with non-English letters. Thanks for feedback!

**Comment by hasoart** [comment]
@Axripov should have been fixed. Can I ask you to try it and report if it worked properly or no?

**Comment by Axripov** [comment]
Yes thanks that helped, but unfortunately that's not what I was looking for)

**Comment by Axripov** [comment]
But your app is also very interesting, I've seen them on YouTube

**Comment by hasoart** [comment]
Great! Nice to hear that! You have seen that I updated the program to support unicode characters right? If not then try it out

**Comment by Axripov** [comment]
I was looking for an application that can store and read video in txt format, if you know one I would be very grateful, just the description and name confused me

**Comment by hasoart** [comment]
To be honest I don't understand what do you mean by storing video in txt file. If you want you can rename your video file into .txt and rename back to the original extension to play it.
